### ISSUE TITLE
2.2 Release

### ISSUE THREAD

**Issue by jjkatz** [jjkatz/AdminProExtension#8]
@aggelosQQ and @DUFCLiam I think we are ready to make a 2.2 release in anticipation of our 3.0 which will be the security update with the logviewer like stuff.

**Comment by jjkatz** [comment]
@DUFCLiam You can make a release. Put 2.2 in the release number. Make a little description and upload the crx. Go into chrome://extensions, developer mode and do pack extension. Disregard the .pem and upload just the .crx.

**Comment by DUFCLiam** [comment]
I know how to I will upload the 2.2 :)

**Comment by DUFCLiam** [comment]
Gotta change something :P Not done yet.

**Comment by jjkatz** [comment]
Thanks. What exactly needs to be changed?

**Comment by DUFCLiam** [comment]
I was thinking the manifest.json file needed changed but nope.

**Comment by aggelosQQ** [comment]
Why are we changing versions so fast?
It should be like 2.2, 2.3 etc.
If we re-write it completely or add something that will change the function completely, then we should update it to 3.0.0
